### ISSUE TITLE
printf vs echo

### ISSUE THREAD

**Issue by timwsuqld** [alexzorin/i3-lastpass#2]
Is there a good reason to use printf instead of echo when passing the items to dmenu?
```bash
LPASS_SELECTION=$(printf "${LPASS_ITEMS}" | dmenu -p "LastPass" -i -l 3)
```

In my branch, when I added the url printing to the list, any url that had % characters (I think they are the culprit) in them would break the printf and the remaining items wouldn't print.
```bash
LPASS_SELECTION=$(echo "${LPASS_ITEMS}" | dmenu -p "LastPass" -i -l 3)
```
Changing it to echo fixed it, but before I submit a merge request, I was wondering if there was a specific reason you had printf?

**Comment by alexzorin** [comment]
I was just testing your PR (thanks by the way, doesn't seem to cause any issues with the old versions of lastpass-cli either) and I noticed the same problem with disappearing entries (triggered by values within the URLs).

I can't think of any reason why I used `printf`.

If you can update your PR to replace all instances of `printf` with `echo`, I'm happy to merge it.

**Comment by timwsuqld** [comment]
#1 PR updated with echo. Thanks
