### ISSUE TITLE
Doesn't copy special characters

### ISSUE THREAD

**Issue by timwsuqld** [alexzorin/i3-lastpass#3]
I have a password that has a > in the password, the > is not copied.

i.e. abcd34>poiu9 becomes abcd34poiu9

This might be a bug in xsel?

**Comment by alexzorin** [comment]
I can't reproduce this, that password copies fine for me (though I think you've accidentally copied the same string twice in your comment).

```
$ dpkg-query -l i3 xsel
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                            Version                      Architecture                 Description
+++-===============================================-============================-============================-===================================================================================================
ii  i3                                              4.15-1~~artful1              amd64                        metapackage (i3 window manager, screen locker, menu, statusbar)
ii  xsel                                            1.2.
```

**Comment by alexzorin** [comment]
Can you tell me if the following works in your environment?

```
echo "abc<def>ghi>" | xsel --secondary -i
```

**Comment by timwsuqld** [comment]
@alexzorin Seems I was mistaken as to where the bug is. The copy works fine. The paste doesn't. Oddly enough though, the paste is only broken when I use my keyboard shortcut (Ubuntu Unity ATM), but if I run the command manually, it works fine. So I think Unity is somehow stuffing up the paste. Really odd.
